### ISSUE TITLE
Listing of custom entity-classes

### ISSUE THREAD

**Issue by andreasobjektvision** [squaredup/HubSpot.NET#1]
@clarkd  I have made some changes to how the List<T>()-methods work. Mainly making the return type for example ContactListHubSpotModel<MyContact> Instead of ContactListHubSpotModel for the returning list. For this to work I have also made the list-classes take a type as a parameter for the contained entity-class.

This is to allow listings of your own entity-classes with custom properties and stuff, without needing to create a list-class. I might have overlooked the need for creating your own list-class though.

Do you want me to make a pull request?

**Comment by clarkd** [comment]
Hey! I think that make sense yeah, please go ahead and make a PR :)

**Comment by clarkd** [comment]
Notably, I've recently done something similar for the Company Properties - it uses `PropertiesListHubSpotModel` which I'll reuse for Contact & Deal properties when I get round to them!

**Comment by clarkd** [comment]
This will fixed by PR #2

**Comment by clarkd** [comment]
Merged in #2
