### ISSUE TITLE
No tests!

### ISSUE THREAD

**Issue by clarkd** [squaredup/HubSpot.NET#12]
We don't currently have any unit tests - with API wrappers like this, they can be difficult to add as you'd have to mock the HubSpot API.

But... we could look at using the HubSpot demo instance (they provide a demo API key etc.) so we could make actual API calls etc.

Any thoughts?

**Comment by bfutrell70** [comment]
Sounds good to me - just having tried the demo key using Postman it appears for GET calls anyway the results are repeatable.

**Comment by clarkd** [comment]
That's good - I think we can avoid any difficulties with repeatability by designing the tests so we only rely on the data we create, e.g.

1. Create a contact
2. Update the same contact
3. Delete the same contact

**Comment by bfutrell70** [comment]
Is there a preference as to which testing framework to use?

**Comment by clarkd** [comment]
I'm pretty flexible really - we use VSTest with Moq for some internal projects but have seen a lot of XUnit around too. Do you have a preference or any relevant experience?

**Comment by bfutrell70** [comment]
The code for our websites use VSTest and Moq but was added later.

I'm currently working on a new project and am using test-driven development
on it with xUnit.

**Comment by clarkd** [comment]
To keep the barrier to entry low and enable anyone to write tests I think looking at VSTest would be a great start. Are you thinking of kicking something off? I'd been to help get the ball rolling so let me know if there's anything I can provide!

**Comment by bfutrell70** [comment]
As soon as I can find a spare moment... :)
