### ISSUE TITLE
Associating a deal with a contact and company

### ISSUE THREAD

**Issue by veganchaos** [squaredup/HubSpot.NET#19]
Hi. This is a fantastic wrapper, so thank you. I am, however, trying to create a deal and associate it with a contact and company, but your deal model doesn’t allow me to add contact and company long[] arrays and assign them to the Associations property. Any assistance you could provide would be appreciated.

**Comment by clarkd** [comment]
You should be able to associate a contact (or company) like this:

```csharp
/**
 * Initialize the API with your API Key
 * You can find or generate this under Integrations -> HubSpot API key
 */
var api = new HubSpotApi("demo");

/**
 * Create a contact
 */
var contact = api.Contact.Create(new ContactHubSpotModel()
{
    Email = "john11@squaredup.com",
    FirstName = "John",
    LastName = "Smith",
    Phone = "00000 000000",
    Company = "Squared Up Ltd."
});

/**
 * Create a deal
 */
var deal = api.Deal.Create(new DealHubSpotModel()
{
    Amount = 10000,
    Name = "New Deal #1",
    Associations = { AssociatedContacts = new []{ contact.Id.Value }} //associate here!
});
```

Is that not working for you?

**Comment by veganchaos** [comment]
It's working perfectly now. Thanks so much for the help!
