### ISSUE TITLE
Deal limit is incorrect

### ISSUE THREAD

**Issue by bfutrell70** [squaredup/HubSpot.NET#22]
HubSpot documentation for Get All Deals describes the Limit optional parameter as defaulting to 100 but has a maximum value of 250.

When I retrieve all deals with a limit of 250 using HubSpot.NET an exception is thrown stating the following:

"Number of items to return must be a positive integer greater than 0, and less than 100 - you provided 250"

**Comment by bfutrell70** [comment]
Caused by the HubSpotDealApi's List<T> method requiring a ListRequestOptions parameter.

ListRequestOptions's Limit property has a upper limit of 100.

**Comment by clarkd** [comment]
This is fixed in 0.6.17 - thanks to @Mark-RSK.
