### ISSUE TITLE
Contact API GetByEmail method causes a HubspotException if the email address is not found

### ISSUE THREAD

**Issue by veganchaos** [squaredup/HubSpot.NET#26]
Was this exception intended to be handled via try/catch (as I am currently doing), or am I doing something wrong? The method works as expected when the e-mail belongs to an existing Contact.

By the way, I am referring to the following method in the Contacts API:

`T GetByEmail<T>(string email) where T : ContactHubSpotModel, new();`

Thanks in advance for your assistance.

**Comment by clarkd** [comment]
I think that's acting as expected - if you're performing a get and there's not an item matching the criteria given, I'd expect it to throw an error. We should perhaps add coverage to the search API side of things which would then allow you to "check" for a given contact by email address etc.

**Comment by veganchaos** [comment]
You're correct, I am performing a get but really just want to know if the contact exists so I can either update it or create a new one. Thanks for the response.

**Comment by clarkd** [comment]
There's a pending PR for a CreateOrUpdate method so that might fulfill your
needs - I'll try and get it released soon!

**Comment by clarkd** [comment]
@veganchaos That's just been released in v0.6.16 - enjoy!

**Comment by veganchaos** [comment]
Awesome! Thanks so much for this.
