### ISSUE TITLE
How to perform a search based on email address without throwing exception?

### ISSUE THREAD

**Issue by ssharma0312** [squaredup/HubSpot.NET#27]
email = "abc@test.com"
var api = new HubSpotApi(hubspotApiKey);
var contact = api.Contact.GetByEmail<ContactHubSpotModel>(email);

here the contact variable throws exception right away, is there any way we use this api to just perform search to check if this email address exist already or not without throwing exception. Since hubspot doesn't allow duplication or overriding so in order for the application to thrown exception, I want to implement alogic to check if contact already exist or not. Thanks in advance

**Comment by clarkd** [comment]
Right now, the only way to achieve that would be to *catch* the exception
but there's an open PR for a CreateOrUpdate they might help going forwards.

**Comment by chrisbaldauf** [comment]
:wave: Chris from HubSpot here.

You may be interested in using the [Contacts Search API Endpoint](https://developers.hubspot.com/docs/methods/contacts/search_contacts), which I've confirmed will not throw an exception if you search for an email that doesn't exist, but rather returns a 200 HTTP status code. The existing `GetByEmail` method could be updated to call that endpoint, or a new `Search` method could be added to maintain backward compatibility for existing callers of the `GetByEmail` method.

```
$ curl "https://api.hubapi.com/contacts/v1/search/query?q=abc@test.com&hapikey=$HAPIKEY"
{
  "query": "abc@test.com",
  "offset": 0,
  "has-more": false,
  "total": 0,
  "contacts": []
}
```

I'd be more than happy to take a look at a PR for this if someone has the time to put one together.

**Comment by clarkd** [comment]
Hi Chris - thanks for reaching out!

That endpoint looks it would work well and would be a great addition to the wrapper. I'd suggest adding it as a new endpoint - overall, we're trying to mirror the HubSpot API and hence the GetByEmail() method still has its place!

**Comment by clarkd** [comment]
We just released version 0.6.16 which includes a contact CreateOrUpdate method which might be helpful here too if that's what you were trying to do?

**Comment by clarkd** [comment]
I'll shortly be releasing v0.6.17 which includes the Search endpoint that @chrisbaldauf mentioned - thanks to @Mark-RSK!

**Comment by Mark-RSK** [comment]
Glad to help. This library has saved me a load of time 👍
