### ISSUE TITLE
Adding Support for the Timeline Events API

### ISSUE THREAD

**Issue by Psypher9** [squaredup/HubSpot.NET#32]
Hello @clarkd,

Would you guys be open to accepting a PR that adds support for the Timeline Events API?

**Comment by TechGuyVN** [comment]
i looking for timeline event api too.

**Comment by Psypher9** [comment]
@rezalas and myself have been working to provide this functionality, as well as including OAuth support.

**Comment by Psypher9** [comment]
We've made quite a few changes at [vtr-dev/HubSpot.NET](https://github.com/vtr-dev/HubSpot.NET). We'll be able to open a PR soon.
