### ISSUE TITLE
Deals list not returning the proper MoreResultsAvailable value

### ISSUE THREAD

**Issue by bfutrell70** [squaredup/HubSpot.NET#4]
As a test I set the deals limit to 10 and the PropertiesToInclude to match the example code { "dealname", "amount" }.

When I look at the object containing the value of MoreResultsAvailable is always false even when there are more records.  The data I am looking at has 500+ deals in it.

To track down where the problem occurs I cloned the repository and stepped through a call to api.Deal.List.  When it gets to the HubSpotBaseClient's SendRequest method with the following signature:

private T SendRequest<T>(string path, Method method, string json, Func<string, T> deserializeFunc) where T : IHubSpotModel, new()

the value of responseData's "hasMore" property is true before deserializeFunc is called.

To verify this I used Postman and performed the same API call with the same parameters and values.

The value of "hasMore" and "offset" match at this point.

![dealsissue](https://user-images.githubusercontent.com/14021233/38745615-092e6072-3f13-11e8-80ed-aaccd1e4881e.PNG)

**Comment by bfutrell70** [comment]
Stepping through the RequestSerializer's DeserializeListEntity method the expandoObject contains the correct "hasMore" value.

Once it is converted from the call to the _requestDataConverter.FromHubSpotListResponse method MoreResultsAvailable becomes false.

![image](https://user-images.githubusercontent.com/14021233/38746048-60362eda-3f14-11e8-89ee-27ed3f661779.png)

**Comment by bfutrell70** [comment]
Found the cause of the issue!

The DealListHubSpotModel's DataMember name for the MoreResultsAvailable property is incorrect.

It is currently "has-more" and should be "hasMore".

**Comment by bfutrell70** [comment]
pull request made for this issue.

**Comment by clarkd** [comment]
Nice one! Thanks @bfutrell70

**Comment by clarkd** [comment]
Fixed in PR #5
