### ISSUE TITLE
Process JSON from a webhook?

### ISSUE THREAD

**Issue by daniel-campbell** [squaredup/HubSpot.NET#43]
Is there a function here which will process the JSON from a POST webhook triggered by a Hubspot Workflow? I want to be able to extract all the info related to the webhook.

**Comment by Psypher9** [comment]
Currently, we don't support the Webhook API. But it sounds like you may need to make an endpoint on your application to listen for the POST request and handle the payload without HubSpot.NET. We are mainly trying to provide a client library to be used internally by .NET applications and not have any external exposure.

**Comment by daniel-campbell** [comment]
Okay, thanks for the quick reply!
