### ISSUE TITLE
Errors when retrieving deals without amounts

### ISSUE THREAD

**Issue by bfutrell70** [squaredup/HubSpot.NET#6]
On the HubSpot web site the Deal Name, Pipeline and Deal Stage are required fields when creating a deal.  Unfortunately unless explicitly specified as a required field in settings a deal amount is not required.

While testing Deals in the example project I found a deal without an amount and an exception was thrown: "Input string was not in a correct format".

**Comment by bfutrell70** [comment]
Fixed in pull request #8

**Comment by clarkd** [comment]
PR merged!
