### ISSUE TITLE
Update package to .Net Standard

### ISSUE THREAD

**Issue by nick-goloborodko** [squaredup/HubSpot.NET#7]
Very useful library. Would be extremely great if it was compatible with .NET standard for use from .Net core and UWP apps

**Comment by bfutrell70** [comment]
I'm using this library with a .NET Core 2.0 console application to call one set of APIs to get quotes out of a website and adding the quotes as deals to HubSpot with a note containing the items in the quote.

So far I haven't had any issues with the package and the code using this package looks much cleaner than my original code to access HubSpot APIs.

**Comment by bfutrell70** [comment]
While it is usable there is a warning for the HubSpot.NET nuget package that it may not be compatible with the project because it was restored using '.NETFramework, Version=v4.6.1' instead of '.NETCoreApp, Version=2.0'.

**Comment by Psypher9** [comment]
HubSpot.NET v1 is currently in preview in the **[v1-preview branch](https://github.com/squaredup/HubSpot.NET/tree/v1-preview)** where we have included support for .NET Standard 2.0 and .NET Framework 4.6.1. 

Please take a look at it and let us know what you think or open a PR to help out! We're hoping to have a version 1 preview package available soon.
